image: docker:latest

services:
  - docker:dind

variables:
  LATEST_VER_HML: caleberios/gaia-esporte:homolog
  LATEST_VER_PROD: caleberios/gaia-esporte:latest

stages:
  - build
  - quality
  - pushImage
  - deploy

buildLocal:
  stage: build
  script:
    - docker build .

testCheck:
  stage: quality
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose run gaiaesporte /bin/sh -c "cd /app; npm i; npm run test"
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

staticAnalysis:
  stage: quality
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose run gaiaesporte /bin/sh -c "cd /app; npm i; npm run lint"

pushHomolog:
  stage: pushImage
  only:
    - dev
  script:
    - docker build -t $LATEST_VER_HML .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_HML && docker image rm $LATEST_VER_HML

pushProd:
  stage: pushImage
  only:
    - master
  script:
    - docker build -t $LATEST_VER_PROD .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_PROD && docker image rm $LATEST_VER_PROD

deployHomolog:
  stage: deploy
  image: google/cloud-sdk
  only:
    - dev
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete svc gaia-esporte-hml
    - kubectl delete deployments gaia-esporte-hml
    - cat k8s/gaia_esporte_hml.yaml | sed "s/{{API_KEY_CLIMA}}/$API_KEY_CLIMA/g" | sed "s/{{API_KEY_LOCAL}}/$API_KEY_LOCAL/g" | sed "s/{{DB}}/$DB/g" | sed "s/{{PASS_DB}}/$PASS_DB/g" | sed "s/{{USER_DB}}/$USER_DB/g" | kubectl apply -f -

deployProd:
  stage: deploy
  image: google/cloud-sdk
  only:
    - master
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete svc gaia-esporte
    - kubectl delete deployments gaia-esporte
    - cat k8s/gaia_esporte.yaml | sed "s/{{API_KEY_CLIMA}}/$API_KEY_CLIMA/g" | sed "s/{{API_KEY_LOCAL}}/$API_KEY_LOCAL/g" | sed "s/{{DB}}/$DB/g" | sed "s/{{PASS_DB}}/$PASS_DB/g" | sed "s/{{USER_DB}}/$USER_DB/g" | kubectl apply -f -
