version: '3'

services:
  gaiaesporte:
    build: .
    restart: always
    environment:
      - API_KEY_LOCAL=${API_KEY_LOCAL}
      - API_KEY_CLIMA=${API_KEY_CLIMA}
      - ENVIRONMENT=dev
      - IP_ADDRESS=${IP_ADDRESS}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: aashreys/mongo-auth:latest
    command: mongod --port 27017
    ports:
      - 27017:27017
